/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        // New palette
        bg: '#07111A',
        panel: '#0E1824',
        panel_soft: '#122233',
        text_primary: '#F8FAFC',
        text_secondary: '#CBD5E1',
        text_muted: '#94A3B8',
        premium_green: '#00A86B',
        gold: '#D4AF37',
        gold_soft: '#F2D27B',
        trust_blue: '#1D9BF0',
        danger_red: '#EF4444',
        // Legacy compat
        bg_primary: '#07111A',
        bg_secondary: '#0E1824',
        bg_tertiary: '#122233',
        elevated_card: '#0E1824',
        elevated_card_soft: '#122233',
        cuboid_blue: '#1D9BF0',
        premium_gold: '#D4AF37',
        trust_green: '#00A86B',
        obsidian: '#07111A',
        pure_white: '#F8FAFC',
        platinum: '#E8EEFF',
        silver_blue: '#94A3B8',
        muted_slate: '#64748B',
        low_emphasis: '#627199',
        electric_blue: '#5E7BFF',
        emerald: '#00A86B',
        institutional_green: '#00A86B',
        amber: '#F59E0B',
        executive_red: '#EF4444',
        crimson: '#EF4444',
      },
      fontFamily: {
        sans: ['Inter Tight', 'Geist', 'Satoshi', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        hero: ['clamp(44px, 6vw, 76px)', { lineHeight: '0.95', letterSpacing: '-0.03em', fontWeight: '800' }],
        subhead: ['24px', { lineHeight: '1.45', fontWeight: '400' }],
        'subhead-mob': ['18px', { lineHeight: '1.45', fontWeight: '400' }],
        section: ['clamp(28px, 3.5vw, 48px)', { lineHeight: '1.05', letterSpacing: '-0.01em', fontWeight: '700' }],
        body: ['17px', { lineHeight: '1.65', fontWeight: '400' }],
        'body-mob': ['16px', { lineHeight: '1.65', fontWeight: '400' }],
        label: ['12px', { lineHeight: '1.2', letterSpacing: '0.08em', fontWeight: '600' }],
        metric: ['52px', { lineHeight: '1.1', fontWeight: '700' }],
        card: ['28px', { lineHeight: '1.3', fontWeight: '600' }],
        xs: ['12px', { lineHeight: '1.2', fontWeight: '400' }],
      },
      borderRadius: {
        btn: '10px',
        input: '12px',
        card: '20px',
        panel: '24px',
        pill: '999px',
        micro: '10px',
        small: '14px',
        medium: '18px',
        large_panel: '32px',
      },
      boxShadow: {
        glow_green: '0 0 40px rgba(0,168,107,0.22)',
        glow_gold: '0 0 40px rgba(212,175,55,0.15)',
        soft: '0 10px 30px rgba(0,0,0,0.18)',
        medium: '0 20px 60px rgba(0,0,0,0.28)',
        premium: '0 40px 120px rgba(0,0,0,0.45)',
      },
      spacing: {
        xs: '8px',
        sm: '12px',
        md: '20px',
        lg: '32px',
        xl: '48px',
        xxl: '72px',
        xxxl: '120px',
        hero_vertical: '160px',
        premium_section: '180px',
        container: '1440px',
        content: '1200px',
        gutter: '48px',
        'gutter-mob': '20px',
        baseline: '8px',
        navbar: '88px',
        ticker: '56px',
        'mob-nav': '74px',
      },
      maxWidth: {
        container: '1440px',
        content: '1200px',
      },
      height: {
        navbar: '88px',
        ticker: '56px',
        'mob-nav': '74px',
        button: '52px',
      },
      backdropBlur: {
        glass: '30px',
      },
      animation: {
        'marquee-slow': 'marquee 50s linear infinite',
        'float': 'float 6s ease-in-out infinite',
        'pulse-soft': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-6px)' },
        },
      },
    },
  },
  plugins: [],
};
