/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        // NEW COLOR SYSTEM - v3 Hero Refactor
        bg_primary: '#020617',
        bg_secondary: '#081225',
        bg_tertiary: '#0B1220',
        elevated_card: '#111827',
        elevated_card_soft: '#152238',
        
        text_primary: '#F8FAFC',
        text_secondary: '#CBD5E1',
        text_muted: '#94A3B8',
        
        cuboid_blue: '#5B7CFF',
        cuboid_blue_hover: '#6F8BFF',
        premium_gold: '#F5B941',
        premium_gold_dark: '#B88916',
        trust_green: '#00C389',
        trust_green_dark: '#009F70',
        warning_orange: '#F97316',
        danger_red: '#EF4444',
        
        // Legacy colors preserved for compatibility
        obsidian: '#020617',
        midnight: '#060D20',
        deep_navy: '#07112B',
        sovereign_blue: '#0B1736',
        elevated_ink: '#0D1B3D',
        panel_navy: '#10214A',
        hover_blue: '#13295B',
        pure_white: '#FFFFFF',
        platinum: '#E8EEFF',
        silver_blue: '#B9C5F2',
        muted_slate: '#7F8DB8',
        low_emphasis: '#627199',
        electric_blue: '#5E7BFF',
        signal_cyan: '#67F7D4',
        gold_primary: '#D6B25E',
        gold_soft: '#E7C979',
        gold_deep: '#B8933D',
        champagne: '#F3E5B8',
        emerald: '#34D399',
        institutional_green: '#22C55E',
        mint_signal: '#6EE7B7',
        amber: '#FBBF24',
        saffron: '#F59E0B',
        executive_red: '#FB7185',
        crimson: '#EF4444',
        rose_alert: '#FDA4AF',
      },
      fontFamily: {
        primary: ['Inter', 'system-ui', 'sans-serif'],
        secondary: ['Geist', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        hero: ['clamp(88px, 9vw, 140px)', { lineHeight: '.92', letterSpacing: '-0.045em', fontWeight: '800' }],
        'hero-title': ['76px', { lineHeight: '0.98', letterSpacing: '-0.04em', fontWeight: '800' }],
        'hero-title-tab': ['56px', { lineHeight: '0.98', letterSpacing: '-0.04em', fontWeight: '800' }],
        'hero-title-mob': ['38px', { lineHeight: '0.98', letterSpacing: '-0.04em', fontWeight: '800' }],
        'hero-sub': ['22px', { lineHeight: '1.65', fontWeight: '400' }],
        'hero-sub-mob': ['17px', { lineHeight: '1.65', fontWeight: '400' }],
        section: ['64px', { lineHeight: '1.05', fontWeight: '700' }],
        'section-title': ['52px', { lineHeight: '1.1', fontWeight: '700' }],
        'section-title-mob': ['34px', { lineHeight: '1.1', fontWeight: '700' }],
        card: ['28px', { lineHeight: '1.3', fontWeight: '600' }],
        metric: ['52px', { lineHeight: '1.1', fontWeight: '700' }],
        body: ['18px', { lineHeight: '1.7', fontWeight: '400' }],
        'body-mob': ['15px', { lineHeight: '1.7', fontWeight: '400' }],
        label: ['12px', { lineHeight: '1.2', letterSpacing: '0.12em', fontWeight: '600' }],
        kicker: ['14px', { lineHeight: '1.2', letterSpacing: '0.16em', fontWeight: '700' }],
      },
      borderRadius: {
        micro: '10px',
        small: '14px',
        medium: '18px',
        card: '24px',
        large_panel: '32px',
        xl: '28px',
        '2xl': '22px',
        pill: '999px',
      },
      boxShadow: {
        soft: '0 10px 30px rgba(0,0,0,.18)',
        medium: '0 20px 60px rgba(0,0,0,.28)',
        premium: '0 40px 120px rgba(0,0,0,.45)',
        glow_blue: '0 0 40px rgba(91,124,255,.28)',
        glow_gold: '0 0 40px rgba(245,185,65,.20)',
        glow_green: '0 0 40px rgba(0,195,137,.20)',
        glow_red: '0 0 0 1px rgba(251,113,133,.10), 0 0 22px rgba(251,113,133,.10)',
      },
      spacing: {
        xs: '8px',
        sm: '12px',
        md: '20px',
        lg: '32px',
        xl: '48px',
        xxl: '72px',
        xxxl: '120px',
        hero_vertical: '160px',
        premium_section: '180px',
        container: '1440px',
        content: '1320px',
        gutter: '48px',
        'gutter-mob': '20px',
        baseline: '8px',
        navbar: '84px',
        ticker: '44px',
        'mob-nav': '78px',
      },
      maxWidth: {
        container: '1440px',
        content: '1320px',
      },
      height: {
        navbar: '84px',
        ticker: '44px',
        'mob-nav': '78px',
        button: '60px',
      },
      backdropBlur: {
        glass: '30px',
      },
      animation: {
        'marquee': 'marquee 40s linear infinite',
        'marquee-fast': 'marquee 25s linear infinite',
        'float': 'float 6s ease-in-out infinite',
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
      },
    },
  },
  plugins: [],
};
